-- DropForeignKey
ALTER TABLE "ORDER_DETAIL" DROP CONSTRAINT "ORDER_DETAIL_securityDetailId_fkey";

-- AlterTable
ALTER TABLE "ORDER_DETAIL" ALTER COLUMN "securityDetailId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "ORDER_DETAIL" ADD CONSTRAINT "ORDER_DETAIL_securityDetailId_fkey" FOREIGN KEY ("securityDetailId") REFERENCES "SECURITY_DETAIL"("id") ON DELETE SET NULL ON UPDATE CASCADE;
