-- DropForeignKey
ALTER TABLE "ACCOUNT_DETAIL" DROP CONSTRAINT "ACCOUNT_DETAIL_orderDetailId_fkey";

-- AlterTable
ALTER TABLE "ACCOUNT_DETAIL" ALTER COLUMN "orderDetailId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "ACCOUNT_DETAIL" ADD CONSTRAINT "ACCOUNT_DETAIL_orderDetailId_fkey" FOREIGN KEY ("orderDetailId") REFERENCES "ORDER_DETAIL"("id") ON DELETE SET NULL ON UPDATE CASCADE;
