export const PAGE_ROUTES = {
   ROOT: '/',
   DASHBOARD: {
      USER_DASHBOARD: '/user/account/dashboard',
      BIDDING: '/user/account/bidding',
      CONSIGNMENTS: '/user/account/consignments',
      WISHLIST: '/user/account/wishlist',
      INVOICE: '/user/account/invoice',
      PROFILE: '/user/account/profile',
      PAYMENT_METHOD: '/user/account/payment-method',
      SEARCH_SETTING: '/user/account/search-setting',
   },
   RETAIL_SHOPPING: {
      CART: '/cart',
      CHECKOUT: '/checkout',
      SHIPPING_OPTION: '/shipping-option',
   },
   RETAIL_PRODUCTS: {
      WINES: '/retail/wines',
      TERMS: '/retail/terms-conditions',
      SPECIAL: '/retail/special',
   },
   AUTH: {
      LOGIN: '/auth/login',
      REGISTER: '/auth/register',
      RESET_PASSWORD: '/auth/reset-password',
      VERIFY_EMAIL: '/auth/verify-email',
      RESEND_VERIFY_EMAIL: '/auth/resend-verify-email',
      LOGOUT: '/auth/logout',
   },
}

export const PAGE_NAMES = {
   [PAGE_ROUTES.DASHBOARD.USER_DASHBOARD]: 'Dashboard',
   [PAGE_ROUTES.DASHBOARD.BIDDING]: 'Bidding',
   [PAGE_ROUTES.DASHBOARD.CONSIGNMENTS]: 'Consignments',
   [PAGE_ROUTES.DASHBOARD.WISHLIST]: 'Wishlist',
   [PAGE_ROUTES.DASHBOARD.INVOICE]: 'Invoice',
   [PAGE_ROUTES.DASHBOARD.PROFILE]: 'Profile',
   [PAGE_ROUTES.DASHBOARD.PAYMENT_METHOD]: 'Payment Methods',
   [PAGE_ROUTES.DASHBOARD.SEARCH_SETTING]: 'Search Settings',
   [PAGE_ROUTES.RETAIL_SHOPPING.CART]: 'Cart',
   [PAGE_ROUTES.RETAIL_SHOPPING.CHECKOUT]: 'Checkout',
   [PAGE_ROUTES.RETAIL_SHOPPING.SHIPPING_OPTION]: 'Shipping Option',
}

export const USER_DASHBOARD_ROUTES_NAME = [
   PAGE_NAMES[PAGE_ROUTES.DASHBOARD.USER_DASHBOARD],
   PAGE_NAMES[PAGE_ROUTES.DASHBOARD.BIDDING],
   PAGE_NAMES[PAGE_ROUTES.DASHBOARD.CONSIGNMENTS],
   PAGE_NAMES[PAGE_ROUTES.DASHBOARD.WISHLIST],
   PAGE_NAMES[PAGE_ROUTES.DASHBOARD.INVOICE],
   PAGE_NAMES[PAGE_ROUTES.DASHBOARD.PROFILE],
   PAGE_NAMES[PAGE_ROUTES.DASHBOARD.PAYMENT_METHOD],
   PAGE_NAMES[PAGE_ROUTES.DASHBOARD.SEARCH_SETTING],
]

export const USER_DASHBOARD_ROUTES = {
   [PAGE_NAMES[PAGE_ROUTES.DASHBOARD.USER_DASHBOARD]]: PAGE_ROUTES.DASHBOARD.USER_DASHBOARD,
   [PAGE_NAMES[PAGE_ROUTES.DASHBOARD.BIDDING]]: PAGE_ROUTES.DASHBOARD.BIDDING,
   [PAGE_NAMES[PAGE_ROUTES.DASHBOARD.CONSIGNMENTS]]: PAGE_ROUTES.DASHBOARD.CONSIGNMENTS,
   [PAGE_NAMES[PAGE_ROUTES.DASHBOARD.WISHLIST]]: PAGE_ROUTES.DASHBOARD.WISHLIST,
   [PAGE_NAMES[PAGE_ROUTES.DASHBOARD.INVOICE]]: PAGE_ROUTES.DASHBOARD.INVOICE,
   [PAGE_NAMES[PAGE_ROUTES.DASHBOARD.PROFILE]]: PAGE_ROUTES.DASHBOARD.PROFILE,
   [PAGE_NAMES[PAGE_ROUTES.DASHBOARD.PAYMENT_METHOD]]: PAGE_ROUTES.DASHBOARD.PAYMENT_METHOD,
   [PAGE_NAMES[PAGE_ROUTES.DASHBOARD.SEARCH_SETTING]]: PAGE_ROUTES.DASHBOARD.SEARCH_SETTING,
}

export const INCLUDE_DASHBOARD_BANNER = [
   PAGE_ROUTES.DASHBOARD.USER_DASHBOARD,
   PAGE_ROUTES.DASHBOARD.BIDDING,
   PAGE_ROUTES.DASHBOARD.CONSIGNMENTS,
   PAGE_ROUTES.DASHBOARD.WISHLIST,
   PAGE_ROUTES.DASHBOARD.INVOICE,
   PAGE_ROUTES.DASHBOARD.PROFILE,
   PAGE_ROUTES.DASHBOARD.PAYMENT_METHOD,
   PAGE_ROUTES.DASHBOARD.SEARCH_SETTING,
]
export const INCLUDE_RETAIL_BANNER = [
   PAGE_ROUTES.RETAIL_PRODUCTS.SPECIAL,
   PAGE_ROUTES.RETAIL_PRODUCTS.WINES,
   PAGE_ROUTES.RETAIL_PRODUCTS.TERMS,
]

export const HIDE_NAV_LINKS = [
   PAGE_ROUTES.AUTH.LOGIN,
   PAGE_ROUTES.AUTH.REGISTER,
   PAGE_ROUTES.AUTH.RESEND_VERIFY_EMAIL,
   PAGE_ROUTES.AUTH.VERIFY_EMAIL,
   PAGE_ROUTES.AUTH.RESET_PASSWORD,
   PAGE_ROUTES.AUTH.LOGOUT,
]

export const HIDE_LOGIN_BUTTON = [PAGE_ROUTES.AUTH.LOGIN]
export const HIDE_NAV_ACTIONS = [...HIDE_NAV_LINKS, PAGE_ROUTES.ROOT]
